cycle:
    databases:
        - { default: true, connection: primary }
        - { default: false, connection: secondary }

    connections:
        primary:
            type: mysql
            dsn: 'mysql:host=mysql;port=3306;dbname=demo'
            user: root
            password: root
        secondary:
            type: mysql
            dsn: 'mysql:host=mysql;port=3306;dbname=demo'
            user: root
            password: root

    orm:
        schema:
            dir: '%kernel.project_dir%/src/Entity'
